// Generated by CoffeeScript 1.10.0
'use strict';
define([], function() {
  var collide, inside, pointInsideRect;
  collide = function(el1, el2) {
    var rect1, rect2;
    rect1 = el1.rect();
    rect2 = el2.rect();
    return !(rect1.top > rect2.bottom || rect1.right < rect2.left || rect1.bottom < rect2.top || rect1.left > rect2.right);
  };
  inside = function(el1, el2) {
    var rect1, rect2;
    rect1 = el1.rect();
    rect2 = el2.rect();
    return ((rect2.top <= rect1.top) && (rect1.top <= rect2.bottom)) && ((rect2.top <= rect1.bottom) && (rect1.bottom <= rect2.bottom)) && ((rect2.left <= rect1.left) && (rect1.left <= rect2.right)) && ((rect2.left <= rect1.right) && (rect1.right <= rect2.right));
  };
  pointInsideRect = function(point, el) {
    var rect;
    rect = el.rect();
    return ((rect.top <= point.y) && (point.y <= rect.bottom)) && ((rect.left <= point.x) && (point.x <= rect.right));
  };
  return {
    collide: collide,
    inside: inside,
    pointInsideRect: pointInsideRect
  };
});
