// Generated by CoffeeScript 1.10.0
'use strict';
define([], function() {
  var chance, inCircle, int, pick;
  int = function(max, min) {
    if (max == null) {
      max = 1;
    }
    if (min == null) {
      min = 0;
    }
    return Math.floor(min + Math.random() * (max + 1 - min));
  };
  chance = function(percentage) {
    return Math.random() * 100 < percentage;
  };
  pick = function(list) {
    return list[int(list.length - 1)];
  };
  inCircle = function(radius) {
    var a, b, ratio, swap;
    a = Math.random();
    b = Math.random();
    if (b < a) {
      swap = b;
      b = a;
      a = swap;
    }
    ratio = a === 0 ? 0 : 2 * Math.PI * a / b;
    return {
      x: b * radius * Math.cos(ratio),
      y: b * radius * Math.sin(ratio)
    };
  };
  return {
    int: int,
    chance: chance,
    pick: pick,
    rand: Math.random,
    inCircle: inCircle
  };
});

//# sourceMappingURL=random.js.map
