// Generated by CoffeeScript 1.10.0
'use strict';
define([], function() {
  var chance, int, pick;
  int = function(max, min) {
    if (max == null) {
      max = 1;
    }
    if (min == null) {
      min = 0;
    }
    return Math.floor(min + Math.random() * (max + 1 - min));
  };
  chance = function(percentage) {
    return Math.random() * 100 < percentage;
  };
  pick = function(list) {
    return list[int(list.length - 1)];
  };
  return {
    int: int,
    chance: chance,
    pick: pick
  };
});
