// Generated by CoffeeScript 1.10.0
'use strict';
define(["wad"], function(Wad) {
  var Sound;
  Sound = (function() {
    function Sound(options) {
      this.sound = new Wad(options);
    }

    Sound.prototype.play = function() {};

    return Sound;

  })();
  return {
    opening: new Sound({
      source: 'sounds/Opening.wav',
      volume: 1
    }),
    explosion: new Sound({
      source: 'sounds/Explosion.wav',
      volume: 1
    }),
    heavyHit: new Sound({
      source: 'sounds/HeavyHit.wav',
      volume: 0.5
    }),
    heavyLaser: new Sound({
      source: 'sounds/HeavyLaser.wav'
    }),
    laser: new Sound({
      source: 'sounds/Laser.wav',
      volume: 0.1
    }),
    pling: new Sound({
      source: 'sounds/Pling.wav'
    }),
    powerup: new Sound({
      source: 'sounds/Powerup.wav'
    })
  };
});
